### ISSUE TITLE
Create preference setting to sort Courses and Subtasks

### ISSUE THREAD

**Issue by owais635** [owais635/planner_flutter#10]
- When a user picks a course we should save it, and use it to sort courses where ever they are shown.
- <img src="https://user-images.githubusercontent.com/25351744/124369991-0d0e7100-dc40-11eb-95be-426c97ae5a4f.jpg"  width="300">

## Places where courses list is shown:
- these should list courses based on user's preference.
- in the course tab list:
    <img src="https://user-images.githubusercontent.com/25351744/124369991-0d0e7100-dc40-11eb-95be-426c97ae5a4f.jpg"  width="300">
- When creating/editing Task:
    <img src="https://user-images.githubusercontent.com/25351744/124370042-9c1b8900-dc40-11eb-83fc-3afaa6de46bf.jpg"  height="500">

**Comment by TheOGApplePie** [comment]
Ok just so I'm understanding this feature well, we're allowing the user to sort their courses via various subfields, right? For example, sort all the courses by their name, or the course code. I'm not sure I understand the Notes section from the first screenshot. Is that just a general link to see all the notes corresponding to the course, or is that also a way to sort the courses? :$

**Comment by owais635** [comment]
> Ok just so I'm understanding this feature well, we're allowing the user to sort their courses via various subfields, right? For example, sort all the courses by their name, or the course code. I'm not sure I understand the Notes section from the first screenshot. Is that just a general link to see all the notes corresponding to the course, or is that also a way to sort the courses? :$ 

No it's not a link but rather a way to sort courses by notes field.
